<a href="https://colab.research.google.com/github/Niko1909/PyTorch-Tutorial/blob/main/torch_tutorial_ch0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tutorial

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.1+cu121


In [ ]:
!nvidia-smi

Thu Sep 19 21:06:34 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
a = torch.tensor(7) # scalar
b = torch.tensor([7]) # vector
c = torch.tensor([7,7]) # vector
d = torch.tensor([[7,7],[7,7]]) # matrix
e = torch.tensor([[[1,2],[1,2]],[[1,2],[1,2]]]) # tensor

In [ ]:
a.ndim, b.ndim, c.ndim, d.ndim, e.ndim

(0, 1, 1, 2, 3)

In [ ]:
a.shape, b.shape, c.shape, d.shape, e.shape

(torch.Size([]),
 torch.Size([1]),
 torch.Size([2]),
 torch.Size([2, 2]),
 torch.Size([2, 2, 2]))

In [ ]:
d[0]

tensor([7, 7])

In [ ]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2010, 0.1348, 0.0453, 0.7075],
        [0.9715, 0.7038, 0.9468, 0.6770],
        [0.9442, 0.0667, 0.3967, 0.5347]])

In [ ]:
zeros = torch.zeros(size=(3,4))
ones = torch.ones(size=(3,4))
zeros, ones

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [ ]:
one_to_ten = torch.arange(start=0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_ones = torch.ones_like(input=one_to_ten)
ten_rand = torch.rand(size=one_to_ten.shape)
ten_zeros, ten_ones, ten_rand

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 tensor([0.6186, 0.4621, 0.7787, 0.0416, 0.4349, 0.1612, 0.2056, 0.7172, 0.4948,
         0.1870, 0.8314]))

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # standard float 32
                               device=None,
                               requires_grad=False)
# float 32 is single precision, float 16 is half precision
# the higher the bits to represent number, faster computing but less precision
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9],
                             dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
(float_32_tensor * int_32_tensor).dtype

torch.float32

In [ ]:
rand_tensor = torch.rand(size=(3,4,2))
rand_tensor

tensor([[[0.1298, 0.2780],
         [0.8747, 0.7344],
         [0.1765, 0.9792],
         [0.6239, 0.8841]],

        [[0.6636, 0.4049],
         [0.0256, 0.0845],
         [0.1527, 0.1534],
         [0.1162, 0.8502]],

        [[0.0718, 0.9935],
         [0.5240, 0.4398],
         [0.5907, 0.8240],
         [0.2199, 0.5132]]])

In [ ]:
rand_tensor.dtype, rand_tensor.shape, rand_tensor.device

(torch.float32, torch.Size([3, 4, 2]), device(type='cpu'))

In [ ]:
tensor = torch.arange(start=0, end=6)
tensor

tensor([0, 1, 2, 3, 4, 5])

In [ ]:
tensor+10, tensor-10, tensor*10, tensor/10,

(tensor([10, 11, 12, 13, 14, 15]),
 tensor([-10,  -9,  -8,  -7,  -6,  -5]),
 tensor([ 0, 10, 20, 30, 40, 50]),
 tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000]))

In [ ]:
torch.mul(tensor, 10), torch.add(tensor, 10)

(tensor([ 0, 10, 20, 30, 40, 50]), tensor([10, 11, 12, 13, 14, 15]))

In [ ]:
tensor=torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [ ]:
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [ ]:
torch.mean(x.type(torch.float32)) # cant do mean on long datatype

tensor(45.)

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
torch.argmin(x), torch.argmax(x)

(tensor(0), tensor(9))

In [ ]:
x[torch.argmin(x)]

tensor(0)

In [ ]:
121/1.5

80.66666666666667

In [ ]:
x = torch.zeros(size=[5,1,5,1])
x.shape, x.squeeze().shape, x.unsqueeze(dim=0).shape

(torch.Size([5, 1, 5, 1]), torch.Size([5, 5]), torch.Size([1, 5, 1, 5, 1]))

In [ ]:
x = torch.rand(size=(224,224,3))
x_permuted = x.permute(dims=(2,0,1))
x_permuted.shape

torch.Size([3, 224, 224])

In [ ]:
x[0,0,0] = 123
x[0,0,0], x_permuted[0,0,0]

(tensor(123.), tensor(123.))

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0,:,2]

tensor([3, 6, 9])

In [ ]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED) # REPRODUCIBILITY

x1 = torch.rand(3,4)
x2 = torch.rand(3,4)
x1, x2

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]]))

In [ ]:
torch.manual_seed(RANDOM_SEED)

x3 = torch.rand(3,4)
x4 = torch.rand(3,4)
x3, x4

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]]))

In [ ]:
x1 == x3, x2 == x4

(tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [ ]:
x = torch.rand(3,4).to(device) # care: numpy cant use GPU tensors -> convert tensor back to cpu before converting it to numpy array
x

tensor([[0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753],
        [0.8860, 0.5832, 0.3376, 0.8090]], device='cuda:0')

# Exercise


In [ ]:
tensor = torch.rand(7,7)
tensor2 = torch.rand(1,7)
tensor @ tensor2.T

tensor([[0.9454],
        [0.9473],
        [0.7089],
        [1.4405],
        [1.3714],
        [0.9152],
        [0.9704]])

In [ ]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
tensor = torch.rand(7,7)
tensor2 = torch.rand(1,7)
tensor @ tensor2.T

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [ ]:
torch.cuda.manual_seed(1234)
device = 'cuda' if torch.cuda.is_available() else 'cpu'
rand1 = torch.rand(size=(2,3), device=device)
rand2 = torch.rand(size=(2,3), device=device) # setting device using .to(device) messes up the reproducibility of the seed
rand1, rand2

(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.6208, 0.0276, 0.3255],
         [0.1114, 0.6812, 0.3608]], device='cuda:0'))

In [ ]:
tensor = rand1 @ rand2.T
tensor

tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')

In [ ]:
tensor.max(), tensor.min()

(tensor(0.7668, device='cuda:0'), tensor(0.2786, device='cuda:0'))

In [ ]:
torch.argmax(tensor), torch.argmin(tensor)

(tensor(1, device='cuda:0'), tensor(0, device='cuda:0'))

In [ ]:
torch.manual_seed(7)
tensor = torch.rand(1,1,1,10)
squeeze_tensor = tensor.squeeze()
squeeze_tensor.shape
print(tensor, tensor.shape)
print(squeeze_tensor, squeeze_tensor.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
